// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PetCareTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginandlogout() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden .w-8")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("ahrustic2");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSWORDDd4?");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addanddeletecategory() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden path")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("epita1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSword3!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Categories")).click();
    driver.findElement(By.cssSelector(".px-6")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Test");
    driver.findElement(By.cssSelector("textarea")).click();
    driver.findElement(By.cssSelector("textarea")).sendKeys("Test");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    js.executeScript("window.scrollTo(0,539.6363525390625)");
    driver.findElement(By.cssSelector("div:nth-child(6) > .btn")).click();
    driver.findElement(By.cssSelector(".mt-5:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addanddeleterase() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.cssSelector(".form-elements")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("epita1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSword3!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Categories")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > article svg")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".px-6")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Small");
    driver.findElement(By.cssSelector("textarea")).click();
    driver.findElement(By.cssSelector("textarea")).sendKeys("Rase");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) > .delete-btn")).click();
    driver.findElement(By.cssSelector("div > .mt-5:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addcommentinpet() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("ahrustic2");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSWORDDd4?");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Find a pet")).click();
    driver.findElement(By.cssSelector("div:nth-child(1) > article .cursor-pointer")).click();
    driver.findElement(By.cssSelector(".px-6")).click();
    driver.findElement(By.name("commentTitle")).click();
    {
      WebElement element = driver.findElement(By.name("commentTitle"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("commentTitle")).sendKeys("Amazing!");
    driver.findElement(By.name("commentContent")).click();
    driver.findElement(By.name("commentContent")).sendKeys("Amazing cat :D");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    js.executeScript("window.scrollTo(0,843.6363525390625)");
    driver.findElement(By.cssSelector(".main-product-image-sm")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addreply() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("ahrustic2");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSWORDDd4?");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".gap-8 > li:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.linkText("Find a pet"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Find a pet")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(5) .cursor-pointer")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".px-6")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".px-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("commentTitle")).click();
    driver.findElement(By.name("commentTitle")).sendKeys("Wow");
    driver.findElement(By.name("commentContent")).click();
    driver.findElement(By.name("commentContent")).sendKeys("Amazing");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("epita1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSword3!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Find a pet")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) path")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".div-btn-reply > .btn")).click();
    driver.findElement(By.name("replyContent")).click();
    driver.findElement(By.name("replyContent")).sendKeys("Yes, great!!!");
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addupdateanddeletecomment() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("alakovic1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Password123!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Find a pet")).click();
    driver.findElement(By.cssSelector("div:nth-child(13) svg")).click();
    driver.findElement(By.cssSelector(".btn-sm")).click();
    js.executeScript("window.scrollTo(0,80.7272720336914)");
    driver.findElement(By.cssSelector("div:nth-child(15) path")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".px-6")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".px-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("commentTitle")).click();
    driver.findElement(By.name("commentTitle")).sendKeys("Test");
    driver.findElement(By.name("commentContent")).click();
    driver.findElement(By.name("commentContent")).sendKeys("Test1");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".div-btn-update > .btn:nth-child(1)")).click();
    driver.findElement(By.name("updateContent")).click();
    driver.findElement(By.name("updateContent")).sendKeys("Test1123");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".div-btn-update > .btn:nth-child(1)")).click();
    driver.findElement(By.name("updateTitle")).click();
    driver.findElement(By.name("updateTitle")).sendKeys("Test13");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addupdateanddeletereply() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden .w-8")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("alakovic1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Password123!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".gap-8 > li:nth-child(3)")).click();
    driver.findElement(By.linkText("Find a pet")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) svg")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".px-6")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".px-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("commentTitle")).click();
    driver.findElement(By.name("commentTitle")).sendKeys("one");
    driver.findElement(By.name("commentContent")).click();
    driver.findElement(By.name("commentContent")).sendKeys("one content");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".div-btn-reply > .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".div-btn-reply > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("replyContent")).click();
    driver.findElement(By.name("replyContent")).sendKeys("ooooo");
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(3)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".uprade-reply-area")).click();
    driver.findElement(By.name("updateReplyContent")).sendKeys("test test");
    driver.findElement(By.cssSelector(".form > .btn")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void incorrectusernameandpassword() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("a");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("a");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.cssSelector(".form-elements")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("ahrustic134");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("afeafafe");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void register() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden path")).click();
    driver.findElement(By.cssSelector("h6 .text-red-500")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Test");
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("Testic");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("test");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("testic@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".Dropdown-placeholder")).click();
    driver.findElement(By.name("password")).sendKeys("Test123!");
    {
      WebElement element = driver.findElement(By.cssSelector(".form-elements"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
  }
  @Test
  public void registervalidation() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden > a > .flex")).click();
    driver.findElement(By.cssSelector("h6 .text-red-500")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("T");
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("T");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("t");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("t");
    driver.findElement(By.name("password")).click();
    js.executeScript("window.scrollTo(0,131.63636779785156)");
    driver.findElement(By.cssSelector(".Dropdown-control")).click();
    driver.findElement(By.name("password")).sendKeys("t");
    driver.findElement(By.cssSelector(".form")).click();
    driver.findElement(By.name("answer")).click();
    driver.findElement(By.name("answer")).sendKeys("t");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("test041@gmail.com");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Test");
    driver.findElement(By.cssSelector(".form")).click();
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("Testic");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("teeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeest");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("testtest");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.cssSelector(".form")).click();
    js.executeScript("window.scrollTo(0,370.18182373046875)");
    driver.findElement(By.cssSelector(".Dropdown-placeholder")).click();
    driver.findElement(By.name("username")).sendKeys("test041");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".form")).click();
    driver.findElement(By.cssSelector(".Dropdown-control")).click();
    driver.findElement(By.cssSelector(".Dropdown-placeholder")).click();
  }
  @Test
  public void validationoffieldsinaddcategoryanddeletemodal() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden .w-8")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("epita1");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("PASSword3!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Categories")).click();
    driver.findElement(By.cssSelector(".div-btn-update")).click();
    driver.findElement(By.cssSelector(".px-6")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".px-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("T");
    driver.findElement(By.cssSelector("textarea")).click();
    driver.findElement(By.cssSelector("textarea")).sendKeys("C");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Test");
    driver.findElement(By.cssSelector(".btn:nth-child(7)")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) .cursor-pointer")).click();
    driver.findElement(By.cssSelector(".btn-sm")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > .btn")).click();
    driver.findElement(By.cssSelector(".ml-4")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > .btn")).click();
    driver.findElement(By.cssSelector(".mt-5:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void addpet() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden .w-8")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("username");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("string123!A");
    driver.findElement(By.cssSelector(".pt-4")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Add pet")).click();
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Mrki");
    driver.findElement(By.name("location")).click();
    driver.findElement(By.name("location")).sendKeys("Sarajevo");
    driver.findElement(By.name("age")).sendKeys("1");
    driver.findElement(By.name("age")).click();
    driver.findElement(By.name("age")).sendKeys("2");
    {
      WebElement element = driver.findElement(By.name("age"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void adoptrequest() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.cssSelector(".hidden path")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("alakovic1");
    driver.findElement(By.name("password")).click();
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("password")).sendKeys("Password123!");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Find a pet")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) .relative path")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".md\\3Aw-1\\/2")).click();
    driver.findElement(By.cssSelector("textarea")).click();
    driver.findElement(By.cssSelector("textarea")).sendKeys("New message");
    driver.findElement(By.cssSelector(".btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".hidden > .flex:nth-child(2)")).click();
  }
  @Test
  public void contectus() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Testic");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("testic@gmail.com");
    driver.findElement(By.name("message")).click();
    driver.findElement(By.name("message")).sendKeys("Help meee!!!");
    driver.findElement(By.cssSelector(".margin-auto")).click();
  }
}
