server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
  security:
    user:
      name: user
      password: password

encrypt:
  key: ruhdghu36878DTFGYuy7eu9heihGDYUHhduehfuieriro009238usG